version: '{build}'
branches:
  only:
  - master
  - /^v\d+(?:\.\d+)?$/
  - /[\b_]validate\b/
skip_tags: true
nuget:
  disable_publish_on_pr: true
image: Visual Studio 2017
configuration: Release
environment:
  VisualStudioVersion: 15.0
init:
  git config --global core.autocrlf true
build_script:
- ps: Build\runbuild.ps1
artifacts:
- path: Working\NuGet\*.nupkg
  name: NuGet Package
