//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("EntityDataModel", "PurchasePurchaseLine", "Purchase", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Newtonsoft.Json.Tests.Purchase), "PurchaseLine", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Newtonsoft.Json.Tests.PurchaseLine))]

// Original file name:
// Generation date: 7/09/2008 7:58:08 p.m.
namespace Newtonsoft.Json.Tests
{
    
    /// <summary>
    /// There are no comments for EntityDataModelContainer in the schema.
    /// </summary>
    public partial class EntityDataModelContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new EntityDataModelContainer object using the connection string found in the 'EntityDataModelContainer' section of the application configuration file.
        /// </summary>
        public EntityDataModelContainer() : 
                base("name=EntityDataModelContainer", "EntityDataModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EntityDataModelContainer object.
        /// </summary>
        public EntityDataModelContainer(string connectionString) : 
                base(connectionString, "EntityDataModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new EntityDataModelContainer object.
        /// </summary>
        public EntityDataModelContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "EntityDataModelContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for PurchaseSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Purchase> PurchaseSet
        {
            get
            {
                if ((this._PurchaseSet == null))
                {
                    this._PurchaseSet = base.CreateQuery<Purchase>("[PurchaseSet]");
                }
                return this._PurchaseSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Purchase> _PurchaseSet;
        /// <summary>
        /// There are no comments for PurchaseLineSet in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<PurchaseLine> PurchaseLineSet
        {
            get
            {
                if ((this._PurchaseLineSet == null))
                {
                    this._PurchaseLineSet = base.CreateQuery<PurchaseLine>("[PurchaseLineSet]");
                }
                return this._PurchaseLineSet;
            }
        }
        private global::System.Data.Objects.ObjectQuery<PurchaseLine> _PurchaseLineSet;
        /// <summary>
        /// There are no comments for PurchaseSet in the schema.
        /// </summary>
        public void AddToPurchaseSet(Purchase purchase)
        {
            base.AddObject("PurchaseSet", purchase);
        }
        /// <summary>
        /// There are no comments for PurchaseLineSet in the schema.
        /// </summary>
        public void AddToPurchaseLineSet(PurchaseLine purchaseLine)
        {
            base.AddObject("PurchaseLineSet", purchaseLine);
        }
    }
    /// <summary>
    /// There are no comments for EntityDataModel.Purchase in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="Purchase")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Purchase : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Purchase object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static Purchase CreatePurchase(int id)
        {
            Purchase purchase = new Purchase();
            purchase.Id = id;
            return purchase;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for PurchaseLine in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "PurchasePurchaseLine", "PurchaseLine")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<PurchaseLine> PurchaseLine
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<PurchaseLine>("EntityDataModel.PurchasePurchaseLine", "PurchaseLine");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<PurchaseLine>("EntityDataModel.PurchasePurchaseLine", "PurchaseLine", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for EntityDataModel.PurchaseLine in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="EntityDataModel", Name="PurchaseLine")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class PurchaseLine : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new PurchaseLine object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        public static PurchaseLine CreatePurchaseLine(int id)
        {
            PurchaseLine purchaseLine = new PurchaseLine();
            purchaseLine.Id = id;
            return purchaseLine;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("EntityDataModel", "PurchasePurchaseLine", "Purchase")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Purchase Purchase
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Purchase>("EntityDataModel.PurchasePurchaseLine", "Purchase").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Purchase>("EntityDataModel.PurchasePurchaseLine", "Purchase").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Purchase in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Purchase> PurchaseReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Purchase>("EntityDataModel.PurchasePurchaseLine", "Purchase");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Purchase>("EntityDataModel.PurchasePurchaseLine", "Purchase", value);
                }
            }
        }
    }
}
